remove /people step from form
ukraine-taskforce/requests-frontend pull request #37
Opened 2022-04-21 12:51 UTC by alisonelizabeth

This PR removes the /people route from the form.

2022-04-21 20:15 UTC, AntonRaichuk requested changes

2022-04-21 20:15 UTC, AntonRaichuk commented on src/medias/translations/en.json
> -  "infants_details": "Under 2",
you forgot to remove the corresponding lines in the uk.json

2022-04-22 00:43 UTC, alisonelizabeth commented on src/medias/translations/en.json
> -  "infants_details": "Under 2",
Good catch! Fixed.

2022-04-22 12:52 UTC, AntonRaichuk approved these changes

2022-04-22 12:52 UTC, merged